#bundle exec jekyll build --config _config.dev.yml
#bundle exec jekyll serve --config _config.dev.yml
theme: jekyll-theme-cayman
title: Cankut's Tech Blog
description: Software, Math and AI
markdown: kramdown
plugins:
  - jemoji
github: 
  is_project_page: false
  is_user_page: true
